### ISSUE TITLE
info.json overrides copy.json (should be clear in docs if that's the case)

### ISSUE THREAD

**Issue by matthewfdaniels** [polygraph-cool/starter#37]

**Comment by russellgoldenberg** [comment]
there is no overriding, they are 2 separate files. each is referenced independently (eg. `<p>{{copy.title}}</p>` and `<p>{{info.title}}</p>` reference two different values from different files. You can totally tweak defaults though (eg. you want to pull everything from `copy`, then you can replace the reference in the hbs files (the only 2 places it is pre-filled are `meta.hbs` and `intro.hbs`).
